#!/usr/bin/env python3
#
# Install git-annex-remote-conp in PATH

from annexremote import Master
from annexremote import SpecialRemote
from annexremote import RemoteError
import urllib.request


class CONPRemote(SpecialRemote):

    def initremote(self):
        pass

    def prepare(self):
        pass

    def transfer_store(self, key, filename):
        raise RemoteError

    def transfer_retrieve(self, key, filename):
        urllib.request.urlretrieve("http://localhost:8080/{}".format(key), filename)

    def checkpresent(self, key):
        try:
            urllib.request.urlopen("http://localhost:8080/{}".format(key))
            return True
        except urllib.request.HTTPError:
            return False

    def remove(self, key):
        raise RemoteError


def main():
    master = Master()
    remote = CONPRemote(master)
    master.LinkRemote(remote)
    master.Listen()

if __name__ == "__main__":
    main()
